### ISSUE TITLE
Что-то можете посоветовать по быстрому переводу с Hystrix на Resilience4j?

### ISSUE THREAD

**Issue by kchvilyov** [homich1991/story-points-converter#1]
Спасибо, Роман.
Даже через 2 года очень помогло в понимании! :)
Что-то можете посоветовать по быстрому переводу с Hystrix на Resilience4j?

**Comment by homich1991** [comment]
@kchvilyov я рад что репозиторий полезен!:)

Честно говоря не подскажу, не успел потыкать Resilience4j.
