### ISSUE TITLE
package com.epam.deepthought does not exist

### ISSUE THREAD

**Issue by kchvilyov** [homich1991/story-points-converter#2]
Что-то не пойму как исправить ошибку построения всего проекта clean install из ветки zool:
Error:(3,28) java: package com.epam.deepthought does not exist
Error:(7,44) java: cannot find symbol

Картинка здесь: https://monosnap.com/file/tDXK4esib5SvvCprRSbMp8zOygjJrA

Запуск: "c:\Program Files\Java\jdk-14.0.1\bin\java.exe" -Dmaven.multiModuleProjectDirectory=C:\Projects\ws-VTB\story-points-converter -Dmaven.home=C:\Java\apache-maven-3.6.1 -Dclassworlds.conf=C:\Java\apache-maven-3.6.1\bin\m2.conf "-Dmaven.ext.class.path=C:\Java\IntelliJ IDEA 2020.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Java\IntelliJ IDEA 2020.1\lib\idea_rt.jar=51912:C:\Java\IntelliJ IDEA 2020.1\bin" -Dfile.encoding=UTF-8 -classpath C:\Java\apache-maven-3.6.1\boot\plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version2020.1.2 clean install

**Comment by homich1991** [comment]
Поймал у себя туже ошибку помогло следующее:
собрал отдельно модуль deep-thought (clean install)

потом нажал кнопку "Reload all maven Projects" на табе Maven (стрелочки по кругу, самая левая кнопку сверху)
